# Site settings
title: Batcher
description: "Batch image processing plug-in for GIMP 3."
baseurl: "/batcher"
url: "https://kamilburda.github.io"
repository: "kamilburda/batcher"
github_username: "Kamil Burda"
copyright_years: "2023-2025"
permalink: /:categories/:year-:month-:day-:slug:output_ext
show_excerpts: true
excerpt_separator: "<!-- end of summary -->"
paginate: 10
paginate_path: "/news/:num/"

plugin_name: "batcher"
plugin_version: "1.0-RC2"
plugin_version_release_date: "February 10, 2025"
download_zip_suffix: ".zip"
sections_url: "/sections/"
news_url: "/news/"
license_remote_url: "blob/main/LICENSE"
license_local_filename: "LICENSE.txt"

plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed

# Build settings
markdown: kramdown
is_release_build: false
