"""Constants used in other modules."""

__all__ = [
  'GIMP_CHARACTER_ENCODING',
  'GIMP_ITEM_PATH_SEPARATOR',
  'TEXT_FILE_ENCODING',
]


GIMP_CHARACTER_ENCODING = 'utf-8'
GIMP_ITEM_PATH_SEPARATOR = '/'
TEXT_FILE_ENCODING = 'utf-8'
