"""Constants used in other modules."""

__all__ = [
  'GTK_CHARACTER_ENCODING',
  'GIMP_CHARACTER_ENCODING',
  'TEXT_FILE_ENCODING',
]


GTK_CHARACTER_ENCODING = 'utf-8'
GIMP_CHARACTER_ENCODING = 'utf-8'
TEXT_FILE_ENCODING = 'utf-8'
